[package]
name = "tm"
description = "tmux helper"
version = "0.5.2"
edition = "2021"
authors = ["Jörg Jaspert <joerg@ganneff.de>"]
license = "BSD-2-Clause"
keywords = [ "tmux", "shell", "helper", "terminal" ]
categories = [ "command-line-utilities" ]
repository = "https://github.com/Ganneff/tm"

[dependencies]
clap = { version = "^3.1.6, ~3.1", features = ["derive", "env", "regex", "unicode", "wrap_help"] }
clap-verbosity-flag = "^1"
flexi_logger = { version = "^0.22", features = ["colors"] }
log = "^0.4"
tmux_interface = { version = "^0.2.0", features = ["tmux_2_8", "cmd_alias"], default-features = false }
quit = "^1.1"
directories = "^4.0"
thiserror = "^1.0"
lazy_static = "^1.4"
anyhow = "^1.0"
rand = "^0.8"
shlex = "1.1.0"

[workspace]
